services:
  spring-mysql:
    image: mysql:latest
    container_name: spring-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=example
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  test-container:
    depends_on:
      spring-mysql:
        condition: service_healthy
    image: lighter-test:0.0.1-SNAPSHOT
    container_name: test-container
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    entrypoint: ["./mvnw", "test"]
    ports:
      - 8080:8080

  spring-app:
    image: lighter:0.0.1-SNAPSHOT
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      spring-mysql:
        condition: service_healthy
      test-container:
        condition: service_completed_successfully
  
  spring-app-dev:
    image: lighter-dev:0.0.1-SNAPSHOT
    container_name: spring-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./src/main:/app/src/main
      - ./src/test:/app/src/test
      - ./target:/app/target
    depends_on:
      spring-mysql:
        condition: service_healthy
      test-container:
        condition: service_completed_successfully

volumes:
  data:
   name: data